// Code generated by MockGen. DO NOT EDIT.
// Source: recommendation.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIRecommendationRepository is a mock of IRecommendationRepository interface.
type MockIRecommendationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRecommendationRepositoryMockRecorder
}

// MockIRecommendationRepositoryMockRecorder is the mock recorder for MockIRecommendationRepository.
type MockIRecommendationRepositoryMockRecorder struct {
	mock *MockIRecommendationRepository
}

// NewMockIRecommendationRepository creates a new mock instance.
func NewMockIRecommendationRepository(ctrl *gomock.Controller) *MockIRecommendationRepository {
	mock := &MockIRecommendationRepository{ctrl: ctrl}
	mock.recorder = &MockIRecommendationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRecommendationRepository) EXPECT() *MockIRecommendationRepositoryMockRecorder {
	return m.recorder
}

// GetCategoryIDsByProductID mocks base method.
func (m *MockIRecommendationRepository) GetCategoryIDsByProductID(arg0 context.Context, arg1 uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryIDsByProductID", arg0, arg1)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryIDsByProductID indicates an expected call of GetCategoryIDsByProductID.
func (mr *MockIRecommendationRepositoryMockRecorder) GetCategoryIDsByProductID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryIDsByProductID", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetCategoryIDsByProductID), arg0, arg1)
}

// GetProductIDsBySubcategoryID mocks base method.
func (m *MockIRecommendationRepository) GetProductIDsBySubcategoryID(ctx context.Context, subcategoryID uuid.UUID, count int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductIDsBySubcategoryID", ctx, subcategoryID, count)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductIDsBySubcategoryID indicates an expected call of GetProductIDsBySubcategoryID.
func (mr *MockIRecommendationRepositoryMockRecorder) GetProductIDsBySubcategoryID(ctx, subcategoryID, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductIDsBySubcategoryID", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetProductIDsBySubcategoryID), ctx, subcategoryID, count)
}

// GetCoPurchasedProductIDs mocks base method.
func (m *MockIRecommendationRepository) GetCoPurchasedProductIDs(ctx context.Context, productID uuid.UUID, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoPurchasedProductIDs", ctx, productID, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoPurchasedProductIDs indicates an expected call of GetCoPurchasedProductIDs.
func (mr *MockIRecommendationRepositoryMockRecorder) GetCoPurchasedProductIDs(ctx, productID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoPurchasedProductIDs", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetCoPurchasedProductIDs), ctx, productID, limit)
}

// GetPreferredSubcategoryIDs mocks base method.
func (m *MockIRecommendationRepository) GetPreferredSubcategoryIDs(ctx context.Context, userID uuid.UUID, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferredSubcategoryIDs", ctx, userID, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferredSubcategoryIDs indicates an expected call of GetPreferredSubcategoryIDs.
func (mr *MockIRecommendationRepositoryMockRecorder) GetPreferredSubcategoryIDs(ctx, userID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferredSubcategoryIDs", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetPreferredSubcategoryIDs), ctx, userID, limit)
}

// GetPurchasedProductIDs mocks base method.
func (m *MockIRecommendationRepository) GetPurchasedProductIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchasedProductIDs", ctx, userID)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchasedProductIDs indicates an expected call of GetPurchasedProductIDs.
func (mr *MockIRecommendationRepositoryMockRecorder) GetPurchasedProductIDs(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchasedProductIDs", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetPurchasedProductIDs), ctx, userID)
}

// GetPopularProductIDs mocks base method.
func (m *MockIRecommendationRepository) GetPopularProductIDs(ctx context.Context, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularProductIDs", ctx, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularProductIDs indicates an expected call of GetPopularProductIDs.
func (mr *MockIRecommendationRepositoryMockRecorder) GetPopularProductIDs(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularProductIDs", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetPopularProductIDs), ctx, limit)
}

// GetComplementaryProductIDs mocks base method.
func (m *MockIRecommendationRepository) GetComplementaryProductIDs(ctx context.Context, purchasedIDs []uuid.UUID, limit int) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComplementaryProductIDs", ctx, purchasedIDs, limit)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComplementaryProductIDs indicates an expected call of GetComplementaryProductIDs.
func (mr *MockIRecommendationRepositoryMockRecorder) GetComplementaryProductIDs(ctx, purchasedIDs, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComplementaryProductIDs", reflect.TypeOf((*MockIRecommendationRepository)(nil).GetComplementaryProductIDs), ctx, purchasedIDs, limit)
}
